// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';
import { getDatabaseUrl } from './src/common/utils';

export default defineConfig({
  schema: 'prisma/',
  migrations: {
    path: 'prisma/migrations',
    seed: 'yarn exec tsx prisma/seed.ts',
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
